import './globals.css'

export const metadata = {
  title: 'Mi primera aplicación',
  description: 'Generated by create next app',
  keywords: 'next,react,app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ul>
          <li>
            <a href="/" >Home</a>
          </li>
          <li>
          <a href="/about" >About</a>
          </li>
          <li>
           <a href="/services" >Services</a>
          </li>
        </ul>
        {children}</body>
    </html>
  )
}
