import Navigation from '../components/Navigation';
import './globals.css';

export const metadata = {
  title: 'Mi primera aplicación',
  description: 'Generated by create next app',
  keywords: 'next,react,app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}</body>
    </html>
  )
}
