import './globals.css'

export const metadata = {
  title: 'Nutrición',
  description: 'Generated by create next app',
  keywords: 'next,react,app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
